spring:
  datasource:
    url: jdbc:h2:mem:Luxnes
    driverClassName: org.h2.Driver
    username: root
    password: ag4035737@
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080
